export const actionType = {
    SHOW_HEADER: 'SHOW_HEADER',
    SHOW_NAV_TAB: "SHOW_NAV_TAB",
    LOGO_POSITION: "LOGO_POSITION",
    COLOR: "COLOR",
    SHOW_LEFT_DRAWER: "SHOW_LEFT_DRAWER",
    SHOW_RIGHT_DRAWER: "SHOW_RIGHT_DRAWER",
    SHOW_FOOTER: "SHOW_FOOTER",
    SHOW_FOOTER_NAV: "SHOW_FOOTER_NAV",
    CURRENT_STEP:"CURRENT_STEP",
    SHOW_OVERLAY:"SHOW_OVERLAY"
}